name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ] # Trigger on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js (if using npm packages/xterm.js)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies and build (example for a Node.js project)
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Replace with your build command

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Change to your build output directory
          keep_files: true # Preserve existing files in gh-pages
